---
title: "wppMarkdown"
author: "Fabian Koch"
date: "14 3 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, warning = FALSE, message = FALSE}
# Dataset
# Data from the United Nations World Population Prospects 2019, released on June 17, 2019
# ?wpp2019
library(wpp2019)
library(tidyverse)
library(patchwork) 
```

```{r echo = FALSE, warning = FALSE, message = FALSE}
data("popF") # age- and sex-specific population estimates and projections
data("popM") # age- and sex-specific population estimates and projections
data("UNlocations") # location dataset

# Female pop estimates
popFemale <- popF %>% mutate(gender = "F")

# Male pop estimates and merge
data_popFM <- popM %>% 
  mutate(gender = "M") %>% 
  # merge
  bind_rows(popFemale) %>% 
  # join country & area codes
  left_join(
    select(
      UNlocations,
      country_code,
      reg_code,
      reg_name,
      area_code,
      area_name),
    by = "country_code") %>% 
  # pad country codes
  mutate(country_code = stringr::str_pad(country_code, 3, pad = "0")) %>% 
  # pop estimates are by 1k population
  mutate(across(where(is.numeric), ~ .*1000))

  
# Extract age levels as factor levels for age groups
age_fctLvl <- data_popFM %>% 
  select(age) %>% 
  distinct() %>% 
  # pull creates vector instead of data.frame
  pull()
  

# im long format ----
data_popFM_long <- data_popFM %>% 
  pivot_longer(
    # cols to unpivot are 4 digit numbers, thus including only years (e.g. 2015 etc) 
    cols = matches("[0-9]{4}"),
    values_to = "population",
    names_to = "year") %>% 
  mutate(
    year = as.numeric(year),
    age = factor(
      age,
      ordered = TRUE,
      levels = age_fctLvl)) 

```


## Themes
### default settings
```{r echo = FALSE, warning = FALSE, message = FALSE}
# default elements
default_font_color <- "black"
default_background_color <- NA # no background color
default_themecolor <- "#044891"
```

### population pyramid
```{r echo = FALSE, warning = FALSE, message = FALSE} 
# population pyramid
theme_ggplot2_popPy <- function(...) {
  theme_minimal()
  theme(
    text = element_text(
      # family = default_font_family,
      color = default_font_color),
    # remove all axes
    axis.line = element_blank(),
    axis.text.x = element_text(
      size = 8, hjust = 0,
      color = default_font_color),
    axis.text.y = element_text(
      margin = unit(c(t = 0, r = -0.7, b = 0, l = 0), "cm")),
    axis.ticks = element_blank(),
    axis.title.y=element_blank(),
    # panel.grid.major = element_blank(),
    # panel.grid.minor = element_blank(),
    # background colors
    plot.background = element_rect(fill = default_background_color,
                                   color = NA),
    panel.background = element_rect(fill = default_background_color,
                                    color = NA),
    legend.background = element_rect(fill = default_background_color,
                                     color = NA),
    # borders and margins
    panel.border = element_blank(),
    panel.spacing = unit(c(0, 0, 0, 0), "cm"),
    # titles
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 7, hjust = 0,
                               color = default_font_color),
    plot.title = element_text(size = 9,
                              color = default_font_color,
                              face = "bold"
                              ),
    plot.subtitle = element_text(size = 7,
                                 color = default_font_color,
                                 margin = margin(b = -0.1,
                                                 t = -0.1,
                                                 l = 2,
                                                 unit = "cm"),
                                 debug = F),
    
  
    plot.caption = element_text(size = 10,
                                hjust = 0,
                                margin = margin(t = 0.2,
                                                b = 0,
                                                unit = "cm"),
                                color = "#939184"),
    ...
  )
  
}
```

## Combining multiple plots

Concepts: 

- arranging multiple Plots w/ {patchwork}

### population pyramid
```{r echo = FALSE, warning = FALSE, message = FALSE}
####
# DATA PREP
####

popPyData <- data_popFM_long %>%
  filter(
    name == "Germany") %>% 
  group_by(
    year,
    name,
    gender) %>%
  mutate(
    percPop_country_gender = round(population/sum(population)*100,1)) %>%
  ungroup() %>%
  # female percentages are later align to the left side of x-axis, thus *-1
  mutate(perc_MF = ifelse(gender == "F", percPop_country_gender*-1, percPop_country_gender)) %>% 
  select(
    year,
    name,
    age,
    gender,
    percPop_country_gender)



####
# PLOT
####

# Bar Charts, left female, right male are showing pop estimates for year 2020

popPyDataBar <- popPyData %>% 
  filter(year == 2020)


popPyDataLine <- popPyData %>% 
  filter(year == 2000)  


# Maxmimum value for x-axis
scale_max <-   
  popPyData %>% 
  select(percPop_country_gender) %>% 
  # max perc
  max() %>% 
  # round up to next integer
  ceiling()


# Bars male
Male <- ggplot() +
  geom_col(  
    data = popPyDataBar[popPyDataBar$gender=="M",], 
    aes(
      x = percPop_country_gender,
      y = age),
    fill = "cornflowerblue",
    alpha = 0.7) +
  geom_line(
      data = popPyDataLine[popPyDataLine$gender=="M",], 
      aes(
        x = percPop_country_gender,
        y = age,
      group = gender),
      orientation = "y",
      color = "midnightblue") +
  theme_ggplot2_popPy() +
  theme(
    plot.margin = unit(c(t = 0, r = 0, b = 0, l = 0), "cm")) +
  scale_x_continuous(
    name = "", 
    limits = c(0, scale_max+1), 
    breaks= scales::breaks_pretty(5), 
    expand = c(0, 1)) + 
  ylab("") +
  # the titles become Plot Tags when stichted together via "patchwork"
  ggtitle("male") +
  # alignment
  theme(plot.title = element_text(hjust=0.08))
   

# Bars female
Female <- ggplot() +
  geom_col(
    data = popPyDataBar[popPyDataBar$gender=="F",], 
    aes(
      x = percPop_country_gender,
      y = age),
    fill = "darkseagreen2") +
  geom_line(
    data = popPyDataLine[popPyDataLine$gender=="F",], 
    aes(
      x = percPop_country_gender,
      y = age,
    group = gender),
    orientation = "y",
    color = "seagreen") +
  theme_ggplot2_popPy() +
  scale_x_reverse(
    name = "", 
  # reverse, since female values are negativ
    limits = c(scale_max+1, 0), 
    breaks= scales::breaks_pretty(5), 
    expand = c(0, 0.1)) +
  theme(
    axis.text.y = element_blank(),
    plot.margin = unit(c(t = 0, r = -2, b = 0, l = 0), "cm")) +
  ylab("") +
  # the titles become Plot Tags when stichted together via "patchwork"
  ggtitle("female") +
  # alignment
  theme(plot.title = element_text(hjust=1))


patchedPy <- Female + Male  +
  patchwork::plot_annotation(
    title = "Changes in gender specific age distribution of german population",
    subtitle = "by age groups, bars: 2020, lines: 2000, in %",
    caption = "Source: dataset wpp2019")
```

```{r echo = FALSE, warning = FALSE, message = FALSE}
patchedPy
```

```{r}
popBarTabData <- data_popFM_long %>%
  filter(
    name == "Germany") %>% 
  filter(year == max(year) | year == max(year)-5) %>%
  group_by(
    year,
    age) %>%
  summarize(population = sum(population)) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(population = round(population/1000,1)) %>% 
  pivot_wider(values_from = population,
              names_from = year) %>% 
  select(
    age,
    contains("0")) %>%
  mutate(
    # selecting by column index in mutate
    age_change_abs = .[[3]] - .[[2]],
    age_change_perc = round((.[[3]]/.[[2]]-1)*100,1)) %>% 
  # calculating mins of more than 1 column
  mutate(min = pmin(.[[3]], .[[2]]),
         max = pmax(.[[3]], .[[2]])) %>%
  filter(!age%in% c("95-99","100+"))


scalemaxBarTab <- max(popBarTabData$max)
scaleminBarTab <- min(popBarTabData$min)


HWBVBarPlot <-   ggplot(popBarTabData) + 
  geom_bar(aes(
    x = age_change_perc, 
    y = age),
           stat = "identity",
           fill = "#044891",
          alpha = 0.8) +
  geom_text(
     aes(
      x = age_change_perc, 
      y = age, 
      label = age_change_perc,
      hjust = ifelse(age_change_perc >= 0, -0.2, 1.2)),    
     size = 3,
     position = position_dodge(width = 1)) +
  geom_text(
    aes(
      x = scalemaxBarTab+0.2, 
      y = age, 
      label = age_change_abs),
    size = 3) 


  coord_cartesian(
    xlim = c(scaleminBarTab-0.2, scalemaxBarTab),
            clip = 'off')  +
    theme_minimal() + 
    theme(plot.margin = unit(c(0,5,1,1), "lines")) +
    labs(
      title = "Veränderung der Hauptwohlbevölkerung ",
      subtitle = "in Stadtbezirken, 31.12.2019 bis 31.12.2020, in % und absolut",
      caption = "",
      tag = "",
      fill = "") +
    xlab("") +
    ylab("") 

```




## Plot annotation

Concepts:

- annotating plots with text and labels
- using different font styles and families
- direct labeling in expense of legend
- arrows and curved lines as pointers


Refrence:

- https://ggplot2.tidyverse.org/reference/annotate.html
- https://ggplot2-book.org/annotations.html
- https://ggplot2.tidyverse.org/reference/geom_segment.html


### line plot
```{r echo = FALSE, warning = FALSE, message = FALSE}
####
# DATA PREP
####

popLineData <- data_popFM_long %>% 
  filter(
      name == "Germany"
      | name == "France") %>%
    group_by(
      name,
      year) %>% 
    summarize(population = sum(population))  %>% 
    mutate(population = round(population/1000000,1)) %>% 
    # mutate(year = as.character(year)) %>% 
    ungroup()


# calculation of label "IncreaseFrance"
valueTextFrance <- popLineData %>% 
  filter(year == 1950 | year == 2020) %>% 
  filter(name == "France") %>% 
  select(population) 
IncreaseFrance <- round(valueTextFrance[1,1]/valueTextFrance[2,1]*100,1)

# geom_point layer "popPointFrance"
popPointFrance <- popLineData %>% 
  filter(name == "France") %>% 
  arrange(year) %>% 
  slice(c(1, n())) 



####
# PLOT
####

popLineGraph <- 
  ggplot(
    popLineData, 
    aes(
      x = year, 
      y = population, 
      group = name, 
      color = name)) +
  geom_line(lwd = 1.2) +
  scale_color_manual(
    values = c(
      "red",
      "black")) +
  # Annotation "German unification"
  annotate(
    # label instead of text
    geom = "label",
    x = 1990,
    y = 75.9,
    # bold type
    fontface = "bold",
    # font family serif
    family = "serif",
    label = "German unification",
    size = 3) +
  # transparent point annotation
  annotate(
    geom="point", 
    x = 1990, 
    y = 78.9, 
    size=5, 
    shape=21, 
    fill="transparent") +
  # Annotation "direct labeling of shown lines"
  annotate(
    geom="Text", 
    x = 2010, 
    y = 78.9, 
    size=4, 
    # # font family sans
    family = "sans",
    label = "Germany",
    fontface =2) +
  annotate(
    geom="text", 
    x = 2010, 
    y = 59, 
    size=4, 
    # font family mono
    family = "mono",
    label = "France",
    color = "red",
    fontface =2) +
  # Annotation pop growth France
  annotate(
    geom = "text", 
    x = 1980, 
    y = 65, 
    size = 3,
    fontface = "italic",
    # adding line breaks in annotation
    label = paste("Increase by\num",IncreaseFrance,"%"),
    hjust = "left") +
  # geom_curve for curved line instead of an arrow
   geom_curve(
     aes(
        x = 1979.5, 
        y = 65, 
        xend = 1950, 
        yend = 43.5),
     curvature = .2) +
  annotate(
    geom = "curve", 
    x = 1987, 
    y = 66, 
    xend = 2019, 
    yend = 66,
    # counter-clockwise curl, and negative values a clockwise curl
    curvature = -.2, 
    arrow = arrow(length = unit(2, "mm"))) + 
    # geom_point France 
  geom_point(
    data = popPointFrance,
    aes(
      x = year,
      y = population), 
    fill = "white",
    alpha = 1,
    shape = 21,
    size = 3,
    stroke = 1.5) +
  geom_text(
    data = popPointFrance,
    aes(
      x = year,
      y = population,
      label = population),
    size = 3,
    nudge_y = -2) +
  theme_minimal() + 
  labs(
      title = "Population trends of Germany and Fance",
      subtitle = "1950 - 2020",
      caption = "",
      tag = "",
      fill = "") +
    xlab("") +
    ylab("Population in millions") +
  theme(legend.position = "none") 


```


```{r echo = FALSE, warning = FALSE, message = FALSE}
popLineGraph
```


## Maps